config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root'home#index'
  get 'about' => 'home#about'
   get'pricing' => 'home#pricing'
  get 'contact' => 'home#contact'
   get 'about'  =>  'home#about'
   
 
   
 
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>About</h1>

app/views/home/contact.html.erb
<h1>Contact</h1><h1>Contact</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>

app/views/home/pricing.html.erb
<h1>Pricing</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Getting Started</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
   <nav class="navbar navbar-expand-md navbar-light bg-light center">
      <div class="container">
        <%= link_to "", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Pricing",pricing_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact",contact_path, class: "nav-link" %></li>
          <li class="nav-item pull-md-right"><%= link_to "Log in In",user_session_path, class: "nav-link" %></li>
          <li class="nav-item float-md-right"><%= link_to "Sign  out",destroy_user_session_path,  method: :delete, class: "nav-link" %></li>
          <li class="nav-item "><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
        
        </ul>
      </div>
    </nav>
 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       
<%= yield %>
   <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>All Right reseverd © 2018 Lee Robertson
          </p>
        </center>
      </div>
    </footer>
</body>
</html>